"""Schemas for the v2 board-onboarding wizard + SDK AI-refinement flow.

Design:
- Phase 1: OnboardingWizardData — pure structured form data, zero LLM involvement.
- Phase 2: OnboardingAIRefinement — result of a single /v1/chat/completions call.
- OnboardingCompleteRequest — combines both phases for final board+agent provisioning.
"""

from __future__ import annotations

from typing import Any, Literal

from sqlmodel import SQLModel

from app.schemas.common import NonEmptyStr

# ---------------------------------------------------------------------------
# Phase 1 — wizard form data (no LLM)
# ---------------------------------------------------------------------------

LeadAgentAutonomyLevel = Literal["ask_first", "balanced", "autonomous"]
LeadAgentVerbosity = Literal["concise", "balanced", "detailed"]
LeadAgentOutputFormat = Literal["bullets", "mixed", "narrative"]
LeadAgentUpdateCadence = Literal["asap", "hourly", "daily", "weekly"]


class OnboardingWizardData(SQLModel):
    """All structured fields collected by the frontend wizard (Phase 1).

    These values come directly from form controls — no agent, no chat session,
    no LLM parsing.  The frontend submits them as-is.
    """

    # Board fields
    board_name: NonEmptyStr
    board_goal: NonEmptyStr
    board_type: Literal["goal", "general"] = "goal"

    # Lead agent fields
    agent_name: NonEmptyStr
    autonomy_level: LeadAgentAutonomyLevel
    verbosity: LeadAgentVerbosity
    output_format: LeadAgentOutputFormat
    update_cadence: LeadAgentUpdateCadence
    custom_instructions: str | None = None

    # User profile
    preferred_name: str | None = None
    pronouns: str | None = None
    timezone: str | None = None


# ---------------------------------------------------------------------------
# Phase 2 — AI refinement (single /v1/chat/completions call)
# ---------------------------------------------------------------------------


class OnboardingAIRefinement(SQLModel):
    """AI-generated refinements returned by Mission Control after Phase 1.

    Generated by a single deterministic POST /v1/chat/completions call using
    the wizard data as context.  The frontend receives this and can display or
    edit it before calling /complete.
    """

    # Refined board goal fields
    objective: str
    description: str
    success_metrics: dict[str, Any] | None = None

    # Lead agent SOUL.md content (full markdown)
    soul_template: str

    # Lead agent identity profile applied at provisioning time
    identity_profile: dict[str, str]  # role, communication_style, emoji


# ---------------------------------------------------------------------------
# Combined request for final board + lead agent provisioning
# ---------------------------------------------------------------------------


class OnboardingCompleteRequest(SQLModel):
    """Combines Phase 1 wizard data and Phase 2 AI refinement.

    Submitted by the frontend once the user confirms the AI-refined results.
    Mission Control uses this to set board fields and provision the lead agent.
    """

    wizard: OnboardingWizardData
    refinement: OnboardingAIRefinement


# ---------------------------------------------------------------------------
# Response schemas
# ---------------------------------------------------------------------------


class OnboardingRefineResponse(SQLModel):
    """Response from POST /refine — the AI-generated refinement payload."""

    refinement: OnboardingAIRefinement
